name: GitHub Actions build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4
      - name: Set up JDK 21
        used: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'graalvm'
      - name: Build with Ant
        run: ant -noinput -buildfile build.xml

